
/*
  --- Predefined Html Colors ---
  Could be using them instead of magic strings
*/

export enum Color {
    White = "white",
    Black = "black",
    Red = "red",
    Green = "green",
    Blue = "blue",
    Yellow = "yellow",
    Orange = "orange",
    Purple = "purple",
    Pink = "pink",
    Brown = "brown",
    Gray = "gray",
    Cyan = "cyan",
    Magenta = "magenta",
    Silver = "silver",
    Gold = "gold",
    Lime = "lime",
    Olive = "olive",
    Maroon = "maroon",
    Teal = "teal",
    Navy = "navy",
    Indigo = "indigo",
    Violet = "violet",
    Turquoise = "turquoise",
    Plum = "plum",
    Coral = "coral",
    Beige = "beige",
    Lavender = "lavender",
    Salmon = "salmon",
    Khaki = "khaki",
    Crimson = "crimson",
    Fuchsia = "fuchsia",
    Azure = "azure",
    Mint = "mint",
    Honeydew = "honeydew",
    Ivory = "ivory",
    Snow = "snow",
    GhostWhite = "ghostwhite",
    Linen = "linen",
    OldLace = "oldlace",
    PapayaWhip = "papayawhip",
    BlanchedAlmond = "blanchedalmond",
    Bisque = "bisque",
    Moccasin = "moccasin",
    NavajoWhite = "navajowhite",
    PeachPuff = "peachpuff",
    MistyRose = "mistyrose",
    LavenderBlush = "lavenderblush",
    Seashell = "seashell",
    Cornsilk = "cornsilk",
    LemonChiffon = "lemonchiffon",
    FloralWhite = "floralwhite",
    AliceBlue = "aliceblue",
    MintCream = "mintcream",
    LightCyan = "lightcyan",
    LightGoldenRodYellow = "lightgoldenrodyellow",
    LightYellow = "lightyellow",
    LightSteelBlue = "lightsteelblue",
    LightSlateGrey = "lightslategrey",
    LightSeaGreen = "lightseagreen",
    LightSalmon = "lightsalmon",
    LightPink = "lightpink",
    LightGray = "lightgray",
    LightGrey = "lightgrey",
    LightGreen = "lightgreen",
    LightCoral = "lightcoral",
    LightBlue = "lightblue",
    LightSkyBlue = "lightskyblue",
    LightSlateGray = "lightslategray",
}